const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('path');
const fs = require('fs');
const {createPreviewApp} = require('../docs/preview/server');
(async()=>{
  const server=createPreviewApp().listen(0,'127.0.0.1');
  await new Promise(resolve=>server.once('listening',resolve));
  let browser;
  try {
    browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
    const page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const base=`http://127.0.0.1:${server.address().port}`;
    await page.goto(base+'/#page-music',{waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>document.querySelectorAll('.record-card').length===3);
    assert.equal(await page.locator('#library-audio').evaluate(a=>a.paused),true);
    await page.locator('.music-search').fill('夜航');assert.equal(await page.locator('.record-card').count(),1);
    await page.locator('.music-type').selectOption('single');assert.equal(await page.locator('.record-card').count(),0);
    await page.locator('.music-search').fill('');assert.equal(await page.locator('.record-card').count(),2);
    await page.locator('.music-category').selectOption('game');assert.equal(await page.locator('.record-card').count(),1);
    await page.locator('.music-type').selectOption('');await page.locator('.music-category').selectOption('');
    await page.locator('.music-listen').click();
    await page.waitForFunction(()=>document.getElementById('library-audio').currentTime>.25);
    assert.equal(await page.locator('#library-audio').evaluate(a=>Math.round(a.duration)),28);
    await page.locator('.player-queue').click();assert.equal(await page.locator('.queue-list button').count(),4);
    await page.locator('.queue-list button').nth(2).click();assert.match(await page.locator('.player-title').innerText(),/Blue Distance/);
    await page.locator('.queue-close').click();
    await page.locator('#sound-toggle').click();assert.equal(await page.locator('#library-audio').evaluate(a=>a.muted),true);
    await page.locator('#sound-toggle').click();
    await page.locator('.player-volume').evaluate(el=>{el.value='.25';el.dispatchEvent(new Event('input',{bubbles:true}));});
    assert.equal(await page.locator('#library-audio').evaluate(a=>a.volume),.25);
    await page.waitForFunction(()=>document.querySelector('#library-audio').duration===28);
    await page.locator('.player-seek').evaluate(el=>{el.value='500';el.dispatchEvent(new Event('input',{bubbles:true}));});
    assert.ok(await page.locator('#library-audio').evaluate(a=>a.currentTime>=14));
    await page.evaluate(()=>goToPage(1));
    assert.equal(await page.locator('#library-audio').evaluate(a=>a.paused),false);
    await page.evaluate(()=>playGM('portal2',document.querySelector('.game-card')));
    assert.equal(await page.evaluate(()=>cA===null),true);
    await page.locator('#library-audio').evaluate(a=>{a.currentTime=27.9;});
    await page.waitForFunction(()=>document.querySelector('.player-title').textContent.includes('Quiet Orbit'));
    await page.locator('.player-toggle').click();assert.equal(await page.locator('#library-audio').evaluate(a=>a.paused),true);
    await page.locator('.player-toggle').click();await page.waitForFunction(()=>!document.getElementById('library-audio').paused);
    await page.locator('.player-close').click();assert.equal(await page.locator('#music-player').isVisible(),false);

    await page.evaluate(()=>goToPage(3));
    await page.locator('.music-add').click();
    const form=page.locator('#music-form');
    await form.locator('[name=title]').fill('上传验证专辑');await form.locator('[name=artist]').fill('本地测试艺术家');
    await form.locator('[name=rating]').selectOption('4');await form.locator('[name=year]').fill('2026');
    await page.waitForFunction(()=>document.querySelector('#music-form [name=related]').options.length>1);
    await form.locator('[name=related]').selectOption('0');
    await form.locator('[name=review]').fill('来自本地上传的两首测试曲目。');
    await form.locator('[name=cover]').setInputFiles(path.resolve('public/media/music/night-ocean.png'));
    await form.locator('[name=tracks]').setInputFiles([path.resolve('docs/preview/music/demo-1.wav'),path.resolve('docs/preview/music/demo-2.wav')]);
    await form.locator('[type=submit]').click();
    const detail=page.locator('#modal-music-detail');
    await page.waitForFunction(()=>document.querySelector('#music-detail-title')?.textContent==='上传验证专辑');
    assert.equal(await detail.locator('.music-track').count(),2);
    await detail.locator('.music-track').first().click();await page.waitForFunction(()=>document.getElementById('library-audio').currentTime>.2);
    assert.match(await page.locator('#library-audio').getAttribute('src'),/^\/music-uploads\//);
    await detail.locator('.music-edit-record').click();
    await form.locator('.music-existing-track input').first().fill('重新命名的曲目');
    await form.locator('.music-existing-track button').last().click();
    await form.locator('[type=submit]').click();
    await page.waitForFunction(()=>document.querySelector('#modal-music-detail .music-track')?.textContent.includes('重新命名的曲目'));
    assert.equal(await detail.locator('.music-track').count(),1);
    assert.equal(await page.locator('.player-title').innerText(),'重新命名的曲目');
    await detail.locator('.music-related').click();assert.equal(await page.locator('#modal-game-detail').getAttribute('aria-hidden'),'false');
    await page.locator('#modal-game-detail .modal-close').click();
    await page.locator('.music-search').fill('上传验证');await page.locator('.record-open').click();
    page.once('dialog',dialog=>dialog.accept());await detail.locator('.music-delete').click();
    await page.waitForFunction(()=>!document.querySelector('#modal-music-detail').classList.contains('show'));
    assert.equal(await page.locator('#music-player').isVisible(),false);
    await page.locator('.music-search').fill('');
    await page.waitForFunction(()=>document.querySelectorAll('.record-card').length===3);
    // Server rejects unsupported uploads without creating a collection record.
    const rejected=await page.request.post(base+'/api/music/upload',{multipart:{tracks:{name:'script.exe',mimeType:'application/octet-stream',buffer:Buffer.from('not audio')}}});
    assert.equal(rejected.status(),400);
    await page.reload({waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>document.querySelectorAll('.record-card').length===3);
    assert.equal(await page.locator('#library-audio').evaluate(a=>a.paused),true);
    await page.evaluate(()=>window.scrollTo(0,document.querySelector('#page-music').offsetTop-76));
    await page.screenshot({path:path.resolve('docs/preview/music-desktop.png')});
    await page.locator('.music-listen').click();await page.waitForFunction(()=>!document.getElementById('library-audio').paused);
    for(const width of [390,320]) {
      await page.setViewportSize({width,height:844});
      await page.evaluate(()=>window.scrollTo(0,document.querySelector('#page-music').offsetTop-66));
      assert.equal(await page.locator('#page-music').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
      assert.equal(await page.locator('#music-player').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
      assert.equal(await page.locator('#navbar').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
      if(width===390)await page.screenshot({path:path.resolve('docs/preview/music-mobile.png')});
    }
    await page.locator('.record-open').first().click();
    assert.equal(await detail.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
    await page.keyboard.press('Escape');
    await page.evaluate(()=>logout());assert.equal(await page.locator('#library-audio').evaluate(a=>a.paused),true);assert.equal(await page.locator('#music-player').isVisible(),false);
    assert.deepEqual(errors,[]);
    console.log('PASS: filters, real playback, queue, seek, volume, global mute, cross-section playback, audio priority, auto-next, upload, edit, relation, delete, reload, mobile, logout.');
  } finally {if(browser)await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
